// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PublicShareOwnerControl.DbAccess;
using System;

namespace PublicShareOwnerControl.Migrations
{
    [DbContext(typeof(OwnerControlContext))]
    [Migration("20180504160023_newInitialMigration")]
    partial class newInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PublicShareOwnerControl.DbAccess.Entities.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StockName");

                    b.Property<int>("UserID");

                    b.HasKey("StockID");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
