// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace StockShareProvider.DbAccess.Migrations
{
    [DbContext(typeof(ProviderContext))]
    [Migration("20180430164347_sellorder2")]
    partial class sellorder2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockShareProvider.DbAccess.Entities.SellOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<decimal>("SellPrice");

                    b.Property<int>("StockID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("SellOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
