// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using TobinTaxControl.DbAccess;

namespace TobinTaxControl.Migrations
{
    [DbContext(typeof(TaxContext))]
    [Migration("20180510114246_initial1")]
    partial class initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TobinTaxControl.DbAccess.Entities.Taxation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("StockID");

                    b.Property<decimal>("TaxPercentage");

                    b.Property<decimal>("TaxSum");

                    b.Property<int>("UserToTaxID");

                    b.HasKey("ID");

                    b.ToTable("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
